// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yfojnhcrhqphqbvsudzj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlmb2puaGNyaHFwaHFidnN1ZHpqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1NDQ4NjIsImV4cCI6MjA3NDEyMDg2Mn0.sl5iAezwvIOj0MnWhNBG6UlrEN-jQ2ivbxePdby1Scg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});